apiVersion: v1
kind: Service
metadata:
  name: flask-showcase-service
spec:
  type: NodePort
  selector:
    app: webapp # Corrected to match deployment labels
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31888
